<?php

// COPYRIGHT (C) HARRY CLARK 2024

// STUDENT NO. 230315257

// CS1_IAD PORTFOLIO 3

// THIS FILE PERTAINS TOWARDS THE MAIN FUNCTIONALITY SURROUNDING THE ENCOMPASSING
// LOGIC OF THE LOGIN PAGE

// THIS WILL TAKE INTO ACCOUNT OF WHICH USERS ARE CURRENTLY WITHIN THE DATABASE
// IN ASSOCIATION WITH THEIR DESIGNATED TAG

class Login
{
    
}

?>